# -*- coding: utf-8 -*-
"""modeling_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mWkUpEdLIh2d3LgXtmuuIaWJHO8MoH27

Dallas Building Permits - Phase 2: ML Modeling Pipeline
========================================================
Two-Stage Hurdle Model:
    Stage 1: XGBoost Classifier (zero vs positive value)
    Stage 2: XGBoost Regressor (predict log_value for positive-value permits)

Includes: Chronological split, baselines, Random Forest, XGBoost + Optuna,
          Stacking Ensemble, SHAP Analysis, K-Means Clustering
"""

import pandas as pd
import numpy as np
import warnings
import os
import joblib
import json
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression, Ridge, LogisticRegression, RidgeClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier, StackingRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    mean_squared_error, mean_absolute_error, r2_score,
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,
    classification_report, confusion_matrix
)
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import xgboost as xgb
import shap
!pip install optuna
import optuna

warnings.filterwarnings("ignore")
optuna.logging.set_verbosity(optuna.logging.WARNING)

# Output directories
os.makedirs("models", exist_ok=True)
os.makedirs("plots", exist_ok=True)

# ============================================================================
# LOAD FEATURE MATRIX
# ============================================================================
print("=" * 70)
print("LOADING DATA")
print("=" * 70)

df = pd.read_csv("permits_features.csv")
df_ids = pd.read_csv("permits_identifiers.csv", parse_dates=["Issued Date"])

print(f"Feature matrix: {df.shape[0]:,} rows x {df.shape[1]} columns")

target_cols = ["Value", "is_zero_value", "log_value"]
feature_cols = [c for c in df.columns if c not in target_cols]
print(f"Features: {len(feature_cols)} | Targets: {target_cols}")

# ============================================================================
# STEP 5: CHRONOLOGICAL TRAIN/VAL/TEST SPLIT
# ============================================================================
print(f"\n{'='*70}")
print("STEP 5: CHRONOLOGICAL TRAIN/VAL/TEST SPLIT")
print(f"{'='*70}")

# Sort by issue date using the identifiers file
df["_issued_date"] = df_ids["Issued Date"].values
df = df.sort_values("_issued_date").reset_index(drop=True)

n = len(df)
train_end = int(n * 0.70)
val_end = int(n * 0.85)

df_train = df.iloc[:train_end].copy()
df_val = df.iloc[train_end:val_end].copy()
df_test = df.iloc[val_end:].copy()

# Drop the temp date column
for d in [df_train, df_val, df_test]:
    d.drop(columns=["_issued_date"], inplace=True)
df.drop(columns=["_issued_date"], inplace=True)

print(f"\n  Split sizes:")
print(f"    Train: {len(df_train):,} rows ({len(df_train)/n*100:.1f}%)")
print(f"    Val:   {len(df_val):,} rows ({len(df_val)/n*100:.1f}%)")
print(f"    Test:  {len(df_test):,} rows ({len(df_test)/n*100:.1f}%)")

# Date ranges
train_dates = df_ids.iloc[:train_end]["Issued Date"]
val_dates = df_ids.iloc[train_end:val_end]["Issued Date"]
test_dates = df_ids.iloc[val_end:]["Issued Date"]

print(f"\n  Date ranges:")
print(f"    Train: {train_dates.min().date()} to {train_dates.max().date()}")
print(f"    Val:   {val_dates.min().date()} to {val_dates.max().date()}")
print(f"    Test:  {test_dates.min().date()} to {test_dates.max().date()}")

print(f"\n  WHY chronological split: A model trained on 2019 data should not be evaluated")
print(f"  on 2018 data. Chronological splitting prevents temporal data leakage and simulates")
print(f"  real-world deployment where the model predicts future permits, not past ones.")

# Prepare feature/target arrays
X_train = df_train[feature_cols].values
X_val = df_val[feature_cols].values
X_test = df_test[feature_cols].values

# Stage 1 targets (all records)
y_train_cls = df_train["is_zero_value"].values
y_val_cls = df_val["is_zero_value"].values
y_test_cls = df_test["is_zero_value"].values

print(f"\n  Stage 1 class balance:")
for name, y in [("Train", y_train_cls), ("Val", y_val_cls), ("Test", y_test_cls)]:
    pos = y.sum()
    print(f"    {name}: {pos} zero ({pos/len(y)*100:.1f}%) | {len(y)-pos} positive ({(len(y)-pos)/len(y)*100:.1f}%)")

# Stage 2 targets (positive-value only)
train_pos = df_train["is_zero_value"] == 0
val_pos = df_val["is_zero_value"] == 0
test_pos = df_test["is_zero_value"] == 0

feature_cols_reg = [c for c in feature_cols if c != 'area_value_ratio']

X_train_reg = df_train.loc[train_pos, feature_cols_reg].values
X_val_reg   = df_val.loc[val_pos,   feature_cols_reg].values
X_test_reg  = df_test.loc[test_pos, feature_cols_reg].values

y_train_reg = df_train.loc[train_pos, 'log_value'].values
y_val_reg   = df_val.loc[val_pos,   'log_value'].values
y_test_reg  = df_test.loc[test_pos, 'log_value'].values

y_train_reg = df_train.loc[train_pos, "log_value"].values
y_val_reg = df_val.loc[val_pos, "log_value"].values
y_test_reg = df_test.loc[test_pos, "log_value"].values

print(f"\n  Stage 2 (positive-value) split:")
print(f"    Train: {len(X_train_reg):,} | Val: {len(X_val_reg):,} | Test: {len(X_test_reg):,}")

# scaler for linear baselines only, two separate scalers for Stage 1 and Stage 2
scaler_cls = StandardScaler()
X_train_cls_scaled = scaler_cls.fit_transform(X_train)
X_val_cls_scaled   = scaler_cls.transform(X_val)
X_test_cls_scaled  = scaler_cls.transform(X_test)

scaler_reg = StandardScaler()
X_train_reg_scaled = scaler_reg.fit_transform(X_train_reg)
X_val_reg_scaled   = scaler_reg.transform(X_val_reg)
X_test_reg_scaled  = scaler_reg.transform(X_test_reg)

joblib.dump(scaler_cls, 'models/scaler_cls.joblib')
joblib.dump(scaler_reg, 'models/scaler_reg.joblib')

# ============================================================================
# STAGE 1: BINARY CLASSIFIER (zero vs positive value)
# ============================================================================
print(f"\n{'='*70}")
print("STAGE 1: BINARY CLASSIFIER")
print(f"{'='*70}")

results_s1 = {}

def eval_classifier(name, y_true, y_pred, y_prob=None):
    """Evaluate and log classifier metrics."""
    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, zero_division=0)
    rec = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    auc = roc_auc_score(y_true, y_prob) if y_prob is not None else 0
    results_s1[name] = {"Accuracy": acc, "Precision": prec, "Recall": rec, "F1": f1, "AUC-ROC": auc}
    print(f"  {name}: Acc={acc:.4f} | Prec={prec:.4f} | Rec={rec:.4f} | F1={f1:.4f} | AUC={auc:.4f}")
    return results_s1[name]

# --- Baseline: Logistic Regression ---
print("\n  [Baseline] Logistic Regression...")
lr_cls = LogisticRegression(max_iter=1000, random_state=42)
lr_cls.fit(X_train_cls_scaled, y_train_cls)
y_pred_lr = lr_cls.predict(X_val_cls_scaled)
y_prob_lr = lr_cls.predict_proba(X_val_cls_scaled)[:, 1]
eval_classifier("Logistic Regression", y_val_cls, y_pred_lr, y_prob_lr)

# --- XGBoost Classifier with Optuna ---
print("\n  [XGBoost] Tuning with Optuna (30 trials)...")

def objective_cls(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 500),
        "max_depth": trial.suggest_int("max_depth", 3, 8),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "eval_metric": "logloss",
        "random_state": 42,
        "n_jobs": -1,
    }
    model = xgb.XGBClassifier(**params)
    # Use cross-validation on training set
    scores = cross_val_score(model, X_train, y_train_cls, cv=3, scoring="f1", n_jobs=-1)
    return scores.mean()

study_cls = optuna.create_study(direction="maximize")
study_cls.optimize(objective_cls, n_trials=30, show_progress_bar=False)

print(f"  Best trial F1 (CV): {study_cls.best_value:.4f}")
print(f"  Best params: {study_cls.best_params}")

# Train final classifier with best params
best_cls_params = study_cls.best_params
best_cls_params["eval_metric"] = "logloss"
best_cls_params["random_state"] = 42
best_cls_params["n_jobs"] = -1

xgb_cls = xgb.XGBClassifier(**best_cls_params)
xgb_cls.fit(X_train, y_train_cls)

y_pred_xgb_cls = xgb_cls.predict(X_val)
y_prob_xgb_cls = xgb_cls.predict_proba(X_val)[:, 1]
eval_classifier("XGBoost Classifier", y_val_cls, y_pred_xgb_cls, y_prob_xgb_cls)

# Test set evaluation
y_pred_xgb_cls_test = xgb_cls.predict(X_test)
y_prob_xgb_cls_test = xgb_cls.predict_proba(X_test)[:, 1]
print(f"\n  [XGBoost Classifier — TEST SET]")
eval_classifier("XGBoost Cls (Test)", y_test_cls, y_pred_xgb_cls_test, y_prob_xgb_cls_test)

# Save classifier
joblib.dump(xgb_cls, "models/stage1_classifier.joblib")
print(f"\n  Saved Stage 1 classifier to models/stage1_classifier.joblib")

# Print classification report
print(f"\n  Classification Report (Test Set):")
print(classification_report(y_test_cls, y_pred_xgb_cls_test,
                            target_names=["Positive-Value", "Zero-Value ($0)"]))

# Stage 1 results table
print(f"\n  Stage 1 Model Comparison:")
print(f"  {'Model':<25} {'Accuracy':>10} {'Precision':>10} {'Recall':>10} {'F1':>10} {'AUC-ROC':>10}")
print(f"  {'-'*75}")
for name, m in results_s1.items():
    print(f"  {name:<25} {m['Accuracy']:>10.4f} {m['Precision']:>10.4f} {m['Recall']:>10.4f} {m['F1']:>10.4f} {m['AUC-ROC']:>10.4f}")

# ============================================================================
# STAGE 2: REGRESSOR (log_value prediction)
# ============================================================================
print(f"\n{'='*70}")
print("STAGE 2: REGRESSOR (predict log_value)")
print(f"{'='*70}")

results_s2 = {}

def eval_regressor(name, y_true, y_pred):
    """Evaluate and log regressor metrics."""
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    # MAPE on back-transformed values
    y_true_usd = np.exp(y_true)
    y_pred_usd = np.exp(y_pred)
    mape = np.mean(np.abs((y_true_usd - y_pred_usd) / np.maximum(y_true_usd, 1))) * 100
    results_s2[name] = {"RMSE": rmse, "MAE": mae, "R2": r2, "MAPE": mape}
    print(f"  {name}: RMSE={rmse:.4f} | MAE={mae:.4f} | R2={r2:.4f} | MAPE={mape:.1f}%")
    return results_s2[name]

# --- Baseline: Linear Regression ---
print("\n  [Baseline] Linear Regression...")
lr_reg = LinearRegression()
lr_reg.fit(X_train_reg_scaled, y_train_reg)
y_pred_lr_reg = lr_reg.predict(X_val_reg_scaled)
eval_regressor("Linear Regression", y_val_reg, y_pred_lr_reg)

# --- Baseline: Ridge Regression ---
print("\n  [Baseline] Ridge Regression (alpha tuning via CV)...")
best_alpha = None
best_r2 = -np.inf
for alpha in [0.01, 0.1, 1.0, 10.0, 100.0]:
    ridge = Ridge(alpha=alpha)
    scores = cross_val_score(ridge, X_train_reg_scaled, y_train_reg, cv=5, scoring="r2")
    mean_r2 = scores.mean()
    if mean_r2 > best_r2:
        best_r2 = mean_r2
        best_alpha = alpha

ridge_reg = Ridge(alpha=best_alpha)
ridge_reg.fit(X_train_reg_scaled, y_train_reg)
y_pred_ridge = ridge_reg.predict(X_val_reg_scaled)
print(f"  Best alpha: {best_alpha} (CV R2: {best_r2:.4f})")
eval_regressor("Ridge Regression", y_val_reg, y_pred_ridge)

# --- Random Forest ---
print("\n  [Random Forest] Training with n_estimators=200...")
rf_reg = RandomForestRegressor(
    n_estimators=200, max_features="sqrt", oob_score=True,
    random_state=42, n_jobs=-1
)
rf_reg.fit(X_train_reg, y_train_reg)
y_pred_rf = rf_reg.predict(X_val_reg)
eval_regressor("Random Forest", y_val_reg, y_pred_rf)
print(f"  OOB Score: {rf_reg.oob_score_:.4f}")

# Feature importance plot for RF
importances = rf_reg.feature_importances_
feat_imp = pd.Series(importances, index=feature_cols_reg).sort_values(ascending=True)
top20 = feat_imp.tail(20)

fig, ax = plt.subplots(figsize=(10, 8))
top20.plot(kind="barh", ax=ax, color="#4C72B0")
ax.set_title("Random Forest — Top 20 Feature Importances (Stage 2)")
ax.set_xlabel("Importance")
plt.tight_layout()
plt.savefig("plots/rf_feature_importance.png", dpi=150)
plt.close()
print(f"  Saved: plots/rf_feature_importance.png")

# --- XGBoost Regressor with Optuna ---
print(f"\n  [XGBoost] Tuning with Optuna (50 trials)...")

def objective_reg(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 1000),
        "max_depth": trial.suggest_int("max_depth", 3, 9),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
        "random_state": 42,
        "n_jobs": -1,
    }
    model = xgb.XGBRegressor(**params)
    scores = cross_val_score(model, X_train_reg, y_train_reg, cv=5, scoring="r2", n_jobs=-1)
    return scores.mean()

study_reg = optuna.create_study(direction="maximize")
study_reg.optimize(objective_reg, n_trials=50, show_progress_bar=False)

print(f"  Best trial R2 (CV): {study_reg.best_value:.4f}")
print(f"  Best params: {json.dumps(study_reg.best_params, indent=2)}")

# Train final model with best params
best_reg_params = study_reg.best_params.copy()
best_reg_params["random_state"] = 42
best_reg_params["n_jobs"] = -1

xgb_reg = xgb.XGBRegressor(**best_reg_params)
xgb_reg.fit(X_train_reg, y_train_reg)

y_pred_xgb_val = xgb_reg.predict(X_val_reg)
eval_regressor("XGBoost", y_val_reg, y_pred_xgb_val)

y_pred_xgb_test = xgb_reg.predict(X_test_reg)
print(f"\n  [XGBoost — TEST SET]")
eval_regressor("XGBoost (Test)", y_test_reg, y_pred_xgb_test)

y_true_usd = np.exp(y_test_reg)
y_pred_usd = np.exp(xgb_reg.predict(X_test_reg))

# look at the distribution of individual percentage errors
pct_errors = np.abs((y_true_usd - y_pred_usd) / np.maximum(y_true_usd, 1)) * 100
print(pd.Series(pct_errors).describe(percentiles=[.25, .5, .75, .90, .95, .99]))

# Save XGBoost model
joblib.dump(xgb_reg, "models/stage2_xgb_regressor.joblib")

# --- Stacking Ensemble ---
print(f"\n  [Stacking Ensemble] RF + XGBoost + Ridge meta-learner...")
estimators = [
    ("rf", RandomForestRegressor(n_estimators=200, max_features="sqrt", random_state=42, n_jobs=-1)),
    ("xgb", xgb.XGBRegressor(**best_reg_params)),
]
stack_reg = StackingRegressor(
    estimators=estimators,
    final_estimator=Ridge(alpha=best_alpha),
    cv=3, n_jobs=-1
)
stack_reg.fit(X_train_reg, y_train_reg)

y_pred_stack_val = stack_reg.predict(X_val_reg)
eval_regressor("Stacking Ensemble", y_val_reg, y_pred_stack_val)

y_pred_stack_test = stack_reg.predict(X_test_reg)
print(f"\n  [Stacking — TEST SET]")
eval_regressor("Stacking (Test)", y_test_reg, y_pred_stack_test)

# --- Final Model Selection ---
print(f"\n  {'='*70}")
print(f"  STAGE 2 MODEL COMPARISON")
print(f"  {'='*70}")
print(f"  {'Model':<25} {'RMSE':>10} {'MAE':>10} {'R2':>10} {'MAPE':>10}")
print(f"  {'-'*65}")
for name, m in results_s2.items():
    print(f"  {name:<25} {m['RMSE']:>10.4f} {m['MAE']:>10.4f} {m['R2']:>10.4f} {m['MAPE']:>9.1f}%")

# Pick best model based on test R2
xgb_test_r2 = results_s2.get("XGBoost (Test)", {}).get("R2", 0)
stack_test_r2 = results_s2.get("Stacking (Test)", {}).get("R2", 0)

if stack_test_r2 > xgb_test_r2 + 0.01:
    final_model = stack_reg
    final_model_name = "Stacking Ensemble"
    joblib.dump(stack_reg, "models/stage2_final_model.joblib")
else:
    final_model = xgb_reg
    final_model_name = "XGBoost"
    joblib.dump(xgb_reg, "models/stage2_final_model.joblib")

print(f"\n  DECISION: Final Stage 2 model = {final_model_name}")
print(f"  WHY: {'Stacking improved R2 by >0.01 over XGBoost alone.' if final_model_name == 'Stacking Ensemble' else 'Stacking did not improve R2 significantly (>0.01). XGBoost is simpler and faster.'}")
print(f"  Saved to: models/stage2_final_model.joblib")

# ============================================================================
# STEP 10: SHAP ANALYSIS
# ============================================================================
print(f"\n{'='*70}")
print("STEP 10: SHAP ANALYSIS (Stage 2 Regressor)")
print(f"{'='*70}")

print("  Computing SHAP values for test set (this may take a minute)...")
explainer = shap.TreeExplainer(xgb_reg)
shap_values = explainer.shap_values(X_test_reg)

# Global: Beeswarm plot
print("  Generating beeswarm summary plot...")
fig, ax = plt.subplots(figsize=(12, 10))
shap.summary_plot(shap_values, X_test_reg, feature_names=feature_cols,
                  show=False, max_display=20)
plt.tight_layout()
plt.savefig("plots/shap_beeswarm.png", dpi=150, bbox_inches="tight")
plt.close()
print("  Saved: plots/shap_beeswarm.png")

# Bar summary plot
fig, ax = plt.subplots(figsize=(12, 8))
shap.summary_plot(shap_values, X_test_reg, feature_names=feature_cols,
                  plot_type="bar", show=False, max_display=20)
plt.tight_layout()
plt.savefig("plots/shap_bar_summary.png", dpi=150, bbox_inches="tight")
plt.close()
print("  Saved: plots/shap_bar_summary.png")

# Dependence plots for top 3 features
mean_abs_shap = np.abs(shap_values).mean(axis=0)
top3_idx = np.argsort(mean_abs_shap)[-3:][::-1]
top3_names = [feature_cols[i] for i in top3_idx]
print(f"  Top 3 SHAP features: {top3_names}")

for i, idx in enumerate(top3_idx):
    name = feature_cols[idx]
    safe_name = name.replace(" ", "_").replace("(", "").replace(")", "")
    fig, ax = plt.subplots(figsize=(8, 6))
    shap.dependence_plot(idx, shap_values, X_test_reg, feature_names=feature_cols,
                         show=False, ax=ax)
    plt.title(f"SHAP Dependence: {name}")
    plt.tight_layout()
    plt.savefig(f"plots/shap_dependence_{safe_name}.png", dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved: plots/shap_dependence_{safe_name}.png")

# Local: Waterfall plots for 3 representative permits
print("\n  Generating waterfall plots for representative permits...")

# Find representative permits in test set
test_ids_subset = df_ids.iloc[val_end:].reset_index(drop=True)
test_values = df_test.loc[test_pos, "Value"].values

# High-value commercial
high_val_idx = np.argmax(test_values)
# Mid-value
mid_val_idx = np.argsort(np.abs(test_values - np.median(test_values)))[0]
# Low-value
low_val_idx = np.argmin(test_values)

for label, idx in [("high_value", high_val_idx), ("mid_value", mid_val_idx), ("low_value", low_val_idx)]:
    explanation = shap.Explanation(
        values=shap_values[idx],
        base_values=explainer.expected_value,
        data=X_test_reg[idx],
        feature_names=feature_cols
    )
    fig, ax = plt.subplots(figsize=(10, 8))
    shap.plots.waterfall(explanation, max_display=15, show=False)
    plt.title(f"SHAP Waterfall: {label.replace('_', ' ').title()} Permit (${test_values[idx]:,.0f})")
    plt.tight_layout()
    plt.savefig(f"plots/shap_waterfall_{label}.png", dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved: plots/shap_waterfall_{label}.png (Value=${test_values[idx]:,.0f})")

# ============================================================================
# STEP 11: K-MEANS CLUSTERING
# ============================================================================
print(f"\n{'='*70}")
print("STEP 11: K-MEANS CLUSTERING")
print(f"{'='*70}")

# Use a subset of features for clustering
cluster_features = ["log_area", "Area", "zip_target_encoded", "land_use_freq",
                     "contractor_permit_count", "days_since_epoch"]
# Add key one-hot features
ohe_cluster = [c for c in feature_cols if c.startswith("sub_category_") or c.startswith("work_type_")]
cluster_features.extend(ohe_cluster)

# target variable excluded from clustering
X_cluster = df[cluster_features].values
cluster_scaler = StandardScaler()
X_cluster_scaled = cluster_scaler.fit_transform(X_cluster)

# Elbow & Silhouette
from sklearn.metrics import silhouette_score

inertias = []
silhouettes = []
K_range = range(2, 11)

print("  Running K-Means for k=2..10...")
for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10, max_iter=300)
    labels = km.fit_predict(X_cluster_scaled)
    inertias.append(km.inertia_)
    sil = silhouette_score(X_cluster_scaled, labels, sample_size=min(10000, len(X_cluster_scaled)))
    silhouettes.append(sil)
    print(f"    k={k}: inertia={km.inertia_:,.0f}, silhouette={sil:.4f}")

# Plot elbow + silhouette
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
ax1.plot(K_range, inertias, "bo-")
ax1.set_xlabel("Number of Clusters (k)")
ax1.set_ylabel("Inertia")
ax1.set_title("Elbow Curve")

ax2.plot(K_range, silhouettes, "ro-")
ax2.set_xlabel("Number of Clusters (k)")
ax2.set_ylabel("Silhouette Score")
ax2.set_title("Silhouette Score vs k")

plt.tight_layout()
plt.savefig("plots/kmeans_elbow_silhouette.png", dpi=150)
plt.close()
print(f"  Saved: plots/kmeans_elbow_silhouette.png")

# Select optimal k based on silhouette peak
optimal_k = list(K_range)[np.argmax(silhouettes)]
print(f"\n  Optimal k = {optimal_k} (highest silhouette score: {max(silhouettes):.4f})")

# Refit at optimal k
km_final = KMeans(n_clusters=optimal_k, random_state=42, n_init=10, max_iter=300)
df["cluster"] = km_final.fit_predict(X_cluster_scaled)

# Cluster profiling
print(f"\n  Cluster Profiles:")
profile_cols = ["Value", "Area", "is_zero_value"]
cluster_profile = df.groupby("cluster").agg(
    count=("Value", "size"),
    mean_value=("Value", "mean"),
    median_value=("Value", "median"),
    mean_area=("Area", "mean"),
    pct_zero=("is_zero_value", "mean"),
).round(2)
cluster_profile["pct_zero"] = (cluster_profile["pct_zero"] * 100).round(1)

print(cluster_profile.to_string())

# Generate cluster names based on profiles
cluster_names = {}
for idx, row in cluster_profile.iterrows():
    if row["pct_zero"] > 50:
        name = "Administrative/Zero-Value"
    elif row["mean_value"] > 200000:
        name = "High-Value Construction"
    elif row["mean_value"] > 50000:
        name = "Mid-Value Commercial/Reno"
    elif row["mean_area"] > 2000:
        name = "Large-Area Projects"
    else:
        name = "Low-Value Residential"

    # Make unique if needed
    suffix = 1
    orig_name = name
    while name in cluster_names.values():
        suffix += 1
        name = f"{orig_name} {suffix}"
    cluster_names[idx] = name

print(f"\n  Cluster Names:")
for k, v in cluster_names.items():
    row = cluster_profile.loc[k]
    print(f"    Cluster {k}: \"{v}\" (n={row['count']:,.0f}, mean=${row['mean_value']:,.0f}, "
          f"{row['pct_zero']}% zero)")

# PCA scatter plot
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_cluster_scaled)

fig, ax = plt.subplots(figsize=(10, 8))
for c in range(optimal_k):
    mask = df["cluster"] == c
    ax.scatter(X_pca[mask, 0], X_pca[mask, 1], alpha=0.3, s=5,
               label=f"C{c}: {cluster_names[c]}")
ax.set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}% variance)")
ax.set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}% variance)")
ax.set_title("Permit Clusters (PCA Projection)")
ax.legend(markerscale=5, fontsize=8)
plt.tight_layout()
plt.savefig("plots/cluster_pca_scatter.png", dpi=150)
plt.close()
print(f"  Saved: plots/cluster_pca_scatter.png")

# Mean value per cluster bar chart
fig, ax = plt.subplots(figsize=(10, 6))
x_labels = [f"C{k}\n{cluster_names[k]}" for k in range(optimal_k)]
values = [cluster_profile.loc[k, "mean_value"] for k in range(optimal_k)]
colors = plt.cm.viridis(np.linspace(0.2, 0.8, optimal_k))
bars = ax.bar(x_labels, values, color=colors)
ax.set_ylabel("Mean Declared Value ($)")
ax.set_title("Mean Permit Value by Cluster")
for bar, val in zip(bars, values):
    ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 1000,
            f"${val:,.0f}", ha="center", va="bottom", fontsize=8)
plt.xticks(fontsize=7)
plt.tight_layout()
plt.savefig("plots/cluster_mean_value.png", dpi=150)
plt.close()
print(f"  Saved: plots/cluster_mean_value.png")

# Save cluster assignments
df[["cluster"]].to_csv("permits_clusters.csv", index=False)

# ============================================================================
# FINAL SUMMARY
# ============================================================================
print(f"\n{'='*70}")
print("PIPELINE COMPLETE - FINAL SUMMARY")
print(f"{'='*70}")

print(f"\n  STAGE 1 — Binary Classifier (Is this a $0 permit?)")
print(f"  Model: XGBoost Classifier")
for name, m in results_s1.items():
    if "Test" in name:
        print(f"  Test: Acc={m['Accuracy']:.4f} | F1={m['F1']:.4f} | AUC={m['AUC-ROC']:.4f}")

print(f"\n  STAGE 2 — Regressor (Predict log_value)")
print(f"  Model: {final_model_name}")
for name, m in results_s2.items():
    if "Test" in name:
        print(f"  Test: RMSE={m['RMSE']:.4f} | MAE={m['MAE']:.4f} | R2={m['R2']:.4f} | MAPE={m['MAPE']:.1f}%")

print(f"\n  FILES SAVED:")
print(f"    models/stage1_classifier.joblib")
print(f"    models/stage2_final_model.joblib ({final_model_name})")
print(f"    models/stage2_xgb_regressor.joblib")
print(f"    models/scaler.joblib")
print(f"    plots/rf_feature_importance.png")
print(f"    plots/shap_beeswarm.png")
print(f"    plots/shap_bar_summary.png")
print(f"    plots/shap_dependence_*.png (3 files)")
print(f"    plots/shap_waterfall_*.png (3 files)")
print(f"    plots/kmeans_elbow_silhouette.png")
print(f"    plots/cluster_pca_scatter.png")
print(f"    plots/cluster_mean_value.png")
print(f"    permits_clusters.csv")

# Save model comparison as JSON for the report
comparison = {
    "stage1": results_s1,
    "stage2": results_s2,
    "final_model": final_model_name,
    "best_xgb_reg_params": best_reg_params,
    "best_xgb_cls_params": best_cls_params,
    "cluster_names": cluster_names,
    "optimal_k": optimal_k,
}
# Convert numpy types for JSON serialization
def convert(obj):
    if isinstance(obj, (np.integer,)): return int(obj)
    if isinstance(obj, (np.floating,)): return float(obj)
    if isinstance(obj, np.ndarray): return obj.tolist()
    return obj

with open("models/model_comparison.json", "w") as f:
    json.dump(comparison, f, indent=2, default=convert)

print(f"\n  Model comparison saved to: models/model_comparison.json")
print(f"\n  Pipeline complete. Ready for Phase 3: Report, Flask API, n8n Agent.")